"use client";

import { useEffect, useRef } from "react";

const features = [
  {
    icon: "🎥",
    title: "AI Video Analysis",
    description:
      "Upload a clip and get frame-by-frame technique analysis with personalized tips from AI. Fix your bandeja, smash, and volleys faster than ever.",
  },
  {
    icon: "🍽️",
    title: "Smart Nutrition",
    description:
      "Snap a photo of your meal — AI identifies macros instantly. Track daily calories with a meal calendar built for athletes.",
  },
  {
    icon: "🏋️",
    title: "Training Plans",
    description:
      "Personalized 7-day training plans generated by AI based on your skill level and goals. Progress at your own pace.",
  },
  {
    icon: "🗺️",
    title: "Find Courts",
    description:
      "Discover padel and tennis courts worldwide. Add your own and earn XP. Find the nearest game, anytime.",
  },
];

function FeatureCard({
  icon,
  title,
  description,
  delay,
}: {
  icon: string;
  title: string;
  description: string;
  delay: number;
}) {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setTimeout(() => el.classList.add("visible"), delay);
          observer.unobserve(el);
        }
      },
      { threshold: 0.1 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [delay]);

  return (
    <div
      ref={ref}
      className="scroll-reveal p-6 rounded-2xl flex flex-col gap-4 transition-all duration-300"
      style={{
        backgroundColor: "rgba(255, 255, 255, 0.04)",
        border: "1px solid rgba(255, 255, 255, 0.08)",
        backdropFilter: "blur(8px)",
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.border = "1px solid rgba(57, 255, 125, 0.2)";
        e.currentTarget.style.boxShadow = "0 0 30px rgba(57, 255, 125, 0.08)";
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.border = "1px solid rgba(255, 255, 255, 0.08)";
        e.currentTarget.style.boxShadow = "none";
      }}
    >
      <div
        className="w-12 h-12 rounded-xl flex items-center justify-center text-2xl"
        style={{ backgroundColor: "rgba(57, 255, 125, 0.1)" }}
      >
        {icon}
      </div>
      <div className="flex flex-col gap-2">
        <h3 className="text-lg font-semibold text-white">{title}</h3>
        <p
          className="text-sm leading-relaxed"
          style={{ color: "rgba(240, 244, 248, 0.6)" }}
        >
          {description}
        </p>
      </div>
    </div>
  );
}

export default function FeaturesSection() {
  const headingRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = headingRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          el.classList.add("visible");
          observer.unobserve(el);
        }
      },
      { threshold: 0.1 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  return (
    <section
      id="features"
      className="py-24 px-4"
      style={{ backgroundColor: "#0b0f14" }}
    >
      <div className="max-w-6xl mx-auto">
        <div ref={headingRef} className="scroll-reveal text-center mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Everything you need to dominate the court
          </h2>
          <p
            className="text-lg max-w-xl mx-auto"
            style={{ color: "rgba(240, 244, 248, 0.6)" }}
          >
            Four powerful tools working together in one app, powered by the
            latest AI.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {features.map((feature, i) => (
            <FeatureCard key={feature.title} {...feature} delay={i * 100} />
          ))}
        </div>
      </div>
    </section>
  );
}
