import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import StructuredData from "@/components/structured-data";
import { APP_IS_LIVE, APP_STORE_ID, BASE_URL } from "@/lib/config";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#050505",
};

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),

  // ── Core ──────────────────────────────────────────────────────────────────
  title: {
    default: "PadelUp — AI Padel Coach App",
    template: "%s | PadelUp",
  },
  description:
    "AI padel coach in your pocket. Frame-by-frame video analysis, personalized training plans, AI nutrition tracking, and 24/7 expert chat. Built for iOS.",
  keywords: [
    "padel coaching app",
    "AI padel coach",
    "padel training app",
    "padel technique analysis",
    "padel video analysis",
    "padel training plan",
    "padel nutrition tracking",
    "AI sports coach",
    "padel improvement app",
    "padel app iOS",
    "padel AI",
    "best padel app",
    "padel racket sport app",
    "padel performance tracker",
    "padel app for beginners",
    "padel app for intermediate players",
    "padel app for advanced players",
    "learn padel",
    "padel drills app",
    "padel strategy app",
    "padel shot analysis",
    "aplicación de pádel",
    "entrenador de pádel AI",
  ],

  // ── Canonical / Alternates ────────────────────────────────────────────────
  alternates: {
    canonical: BASE_URL,
    languages: {
      "x-default": BASE_URL,
      en: BASE_URL,
    },
  },

  // ── Robots ────────────────────────────────────────────────────────────────
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // ── Search engine verification (add real codes from each console) ─────────
  verification: {
    google: "", // add from Google Search Console
    yandex: "", // add from Yandex Webmaster
    other: {
      "msvalidate.01": "", // Bing Webmaster
    },
  },

  // ── Open Graph ────────────────────────────────────────────────────────────
  // Note: images are auto-generated by /app/opengraph-image.tsx and
  // per-route opengraph-image files. Next.js injects the tags automatically.
  openGraph: {
    type: "website",
    locale: "en_US",
    url: BASE_URL,
    siteName: "PadelUp",
    title: "PadelUp — AI Padel Coach App",
    description:
      "Frame-by-frame technique analysis, personalized training plans, and AI nutrition tracking. The padel coach in your pocket.",
  },

  // ── Twitter / X ───────────────────────────────────────────────────────────
  twitter: {
    card: "summary_large_image",
    title: "PadelUp — AI Padel Coach App",
    description:
      "Frame-by-frame technique analysis, personalized training plans, AI nutrition tracking. The padel coach in your pocket.",
  },

  // ── App-specific / ASO ────────────────────────────────────────────────────
  // Smart App Banner — activated once APP_STORE_ID is set in src/lib/config.ts
  ...(APP_IS_LIVE && APP_STORE_ID
    ? {
        appLinks: {
          ios: {
            app_store_id: APP_STORE_ID,
            url: `https://apps.apple.com/app/padelup/id${APP_STORE_ID}`,
          },
        },
        itunes: { appId: APP_STORE_ID },
      }
    : {}),

  // ── App / PWA meta ────────────────────────────────────────────────────────
  appleWebApp: {
    capable: true,
    title: "PadelUp",
    statusBarStyle: "black-translucent",
    startupImage: ["/og-image.png"],
  },

  // ── Favicons / App Icons ─────────────────────────────────────────────────
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.png", type: "image/png", sizes: "512x512" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
    shortcut: "/favicon.ico",
  },

  // ── Authorship ────────────────────────────────────────────────────────────
  authors: [{ name: "PadelUp", url: BASE_URL }],
  creator: "PadelUp",
  publisher: "PadelUp",
  category: "Sports",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        {/* Preconnect to font providers for faster loading */}
        <link rel="preconnect" href="https://api.fontshare.com" />
        <link rel="dns-prefetch" href="https://api.fontshare.com" />
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@200,300,400,500,600,700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@300,400,500,700&display=swap"
          rel="stylesheet"
        />
        <StructuredData />
      </head>
      <body className="min-h-full flex flex-col bg-[#050505] text-[#f0f4f8]">
        {children}
        <Analytics />
        <Script id="microsoft-clarity" strategy="afterInteractive">
          {`(function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i+"?ref=bwt";
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
          })(window, document, "clarity", "script", "wb1lb6hljq");`}
        </Script>
      </body>
    </html>
  );
}
